// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_rolling_support_resistance_fast
DataFrame calculate_rolling_support_resistance_fast(CharacterVector dates, NumericVector opens, NumericVector highs, NumericVector lows, NumericVector closes, NumericVector volumes, NumericVector adjusted, int window_size, int width);
RcppExport SEXP _hmmTradeR_calculate_rolling_support_resistance_fast(SEXP datesSEXP, SEXP opensSEXP, SEXP highsSEXP, SEXP lowsSEXP, SEXP closesSEXP, SEXP volumesSEXP, SEXP adjustedSEXP, SEXP window_sizeSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type dates(datesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type opens(opensSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type highs(highsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lows(lowsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type closes(closesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type volumes(volumesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adjusted(adjustedSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_rolling_support_resistance_fast(dates, opens, highs, lows, closes, volumes, adjusted, window_size, width));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hmmTradeR_calculate_rolling_support_resistance_fast", (DL_FUNC) &_hmmTradeR_calculate_rolling_support_resistance_fast, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_hmmTradeR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
