// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculate_rolling_support_resistance_fast
DataFrame calculate_rolling_support_resistance_fast(CharacterVector dates, NumericVector opens, NumericVector highs, NumericVector lows, NumericVector closes, NumericVector volumes, NumericVector adjusted, int window_size, int width);
RcppExport SEXP _hmmTradeR_calculate_rolling_support_resistance_fast(SEXP datesSEXP, SEXP opensSEXP, SEXP highsSEXP, SEXP lowsSEXP, SEXP closesSEXP, SEXP volumesSEXP, SEXP adjustedSEXP, SEXP window_sizeSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type dates(datesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type opens(opensSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type highs(highsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lows(lowsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type closes(closesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type volumes(volumesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type adjusted(adjustedSEXP);
    Rcpp::traits::input_parameter< int >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_rolling_support_resistance_fast(dates, opens, highs, lows, closes, volumes, adjusted, window_size, width));
    return rcpp_result_gen;
END_RCPP
}
// optimize_walk_forward_hmm_cpp
List optimize_walk_forward_hmm_cpp(const arma::mat& X_all, IntegerVector nstates_cand, IntegerVector n_bull_cand, IntegerVector n_bear_cand, int training_frequency, int initial_multiplier, int seed, int maxit, double tol, double cov_reg, bool parallel, bool verbose);
RcppExport SEXP _hmmTradeR_optimize_walk_forward_hmm_cpp(SEXP X_allSEXP, SEXP nstates_candSEXP, SEXP n_bull_candSEXP, SEXP n_bear_candSEXP, SEXP training_frequencySEXP, SEXP initial_multiplierSEXP, SEXP seedSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP cov_regSEXP, SEXP parallelSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_all(X_allSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nstates_cand(nstates_candSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_bull_cand(n_bull_candSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_bear_cand(n_bear_candSEXP);
    Rcpp::traits::input_parameter< int >::type training_frequency(training_frequencySEXP);
    Rcpp::traits::input_parameter< int >::type initial_multiplier(initial_multiplierSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type cov_reg(cov_regSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_walk_forward_hmm_cpp(X_all, nstates_cand, n_bull_cand, n_bear_cand, training_frequency, initial_multiplier, seed, maxit, tol, cov_reg, parallel, verbose));
    return rcpp_result_gen;
END_RCPP
}
// walk_forward_hmm_cpp
List walk_forward_hmm_cpp(const arma::mat& X_all, int nstates, int n_bull, int n_bear, std::string mode_select, double percentile_cut, int seed, int training_frequency, int initial_multiplier, int maxit, double tol, bool verbose);
RcppExport SEXP _hmmTradeR_walk_forward_hmm_cpp(SEXP X_allSEXP, SEXP nstatesSEXP, SEXP n_bullSEXP, SEXP n_bearSEXP, SEXP mode_selectSEXP, SEXP percentile_cutSEXP, SEXP seedSEXP, SEXP training_frequencySEXP, SEXP initial_multiplierSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_all(X_allSEXP);
    Rcpp::traits::input_parameter< int >::type nstates(nstatesSEXP);
    Rcpp::traits::input_parameter< int >::type n_bull(n_bullSEXP);
    Rcpp::traits::input_parameter< int >::type n_bear(n_bearSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode_select(mode_selectSEXP);
    Rcpp::traits::input_parameter< double >::type percentile_cut(percentile_cutSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type training_frequency(training_frequencySEXP);
    Rcpp::traits::input_parameter< int >::type initial_multiplier(initial_multiplierSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(walk_forward_hmm_cpp(X_all, nstates, n_bull, n_bear, mode_select, percentile_cut, seed, training_frequency, initial_multiplier, maxit, tol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// forward_probs_live_cpp
arma::vec forward_probs_live_cpp(const arma::mat& X_recent, const arma::vec& pi, const arma::mat& A, const arma::mat& mu, const Rcpp::List& Sigma_inv_list, const arma::vec& logdetSigma);
RcppExport SEXP _hmmTradeR_forward_probs_live_cpp(SEXP X_recentSEXP, SEXP piSEXP, SEXP ASEXP, SEXP muSEXP, SEXP Sigma_inv_listSEXP, SEXP logdetSigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_recent(X_recentSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pi(piSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Sigma_inv_list(Sigma_inv_listSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type logdetSigma(logdetSigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(forward_probs_live_cpp(X_recent, pi, A, mu, Sigma_inv_list, logdetSigma));
    return rcpp_result_gen;
END_RCPP
}
// update_hmm_online_cpp
List update_hmm_online_cpp(List model, arma::vec x_new, double learning_rate);
RcppExport SEXP _hmmTradeR_update_hmm_online_cpp(SEXP modelSEXP, SEXP x_newSEXP, SEXP learning_rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_new(x_newSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    rcpp_result_gen = Rcpp::wrap(update_hmm_online_cpp(model, x_new, learning_rate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hmmTradeR_calculate_rolling_support_resistance_fast", (DL_FUNC) &_hmmTradeR_calculate_rolling_support_resistance_fast, 9},
    {"_hmmTradeR_optimize_walk_forward_hmm_cpp", (DL_FUNC) &_hmmTradeR_optimize_walk_forward_hmm_cpp, 12},
    {"_hmmTradeR_walk_forward_hmm_cpp", (DL_FUNC) &_hmmTradeR_walk_forward_hmm_cpp, 12},
    {"_hmmTradeR_forward_probs_live_cpp", (DL_FUNC) &_hmmTradeR_forward_probs_live_cpp, 6},
    {"_hmmTradeR_update_hmm_online_cpp", (DL_FUNC) &_hmmTradeR_update_hmm_online_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_hmmTradeR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
