# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_rolling_support_resistance_fast <- function(dates, opens, highs, lows, closes, volumes, adjusted, window_size = 100L, width = 20L) {
    .Call(`_hmmTradeR_calculate_rolling_support_resistance_fast`, dates, opens, highs, lows, closes, volumes, adjusted, window_size, width)
}

